import java.util.ArrayList;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue() {
        /* to be implemented in part (a) */
        double totalRevenue = 0;
        for(Flight flight : allFlights) {
            int capacity = flight.getCapacity();
            int passengers = flight.getNumPassengers();
            double price = flight.getPrice();
            if (flight.getNumPassengers() > flight.getCapacity()) {
                totalRevenue += price * capacity;
            }
            else {
                totalRevenue += price * passengers;
            }
        }
        return totalRevenue;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int totalPassengers = 0;
        for(int i = 0; i < allFlights.size(); i++) {
            double percentage = (double) allFlights.get(i).getNumPassengers() / allFlights.get(i).getCapacity();
            if (percentage < 0.2) {
                totalPassengers += allFlights.get(i).getNumPassengers();
                allFlights.remove(i);
                i--;
            }
        }
        return totalPassengers;
    }
}